# Generated by Django 2.1.5 on 2019-02-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
