# Generated by Django 2.1.5 on 2019-02-06 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyst', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='FeedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.TextField()),
                ('message', models.TextField()),
                ('card_key', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_cards', related_query_name='feed_card', to='analyst.Question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_cards', related_query_name='feed_card', to='accounts.Team')),
            ],
            options={
                'ordering': ('team', 'updated', 'created'),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='feed_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='feed.FeedCard'),
        ),
        migrations.AddField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='accounts.Team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adept',
            name='feed_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adepts', related_query_name='adept', to='feed.FeedCard'),
        ),
        migrations.AddField(
            model_name='adept',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adepts', related_query_name='adept', to='accounts.Team'),
        ),
        migrations.AddField(
            model_name='adept',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adepts', related_query_name='adept', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='feedcard',
            unique_together={('team', 'question', 'card_key')},
        ),
        migrations.AlterUniqueTogether(
            name='adept',
            unique_together={('team', 'user', 'feed_card')},
        ),
    ]
