# Generated by Django 2.1.5 on 2019-02-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MySQL', 'MySQL')], max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('ssh_tunnel', models.TextField(default='{}')),
                ('connection', models.TextField(default='{}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', related_query_name='data_source', to='accounts.Team')),
            ],
            options={
                'ordering': ['created', 'team'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('query', models.TextField()),
                ('publish', models.BooleanField(default=False)),
                ('cron', models.CharField(default='0 9 * * *', max_length=100)),
                ('last_run_start_time', models.DateTimeField(blank=True, null=True)),
                ('last_run_end_time', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_run_time', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('chart_type', models.CharField(choices=[('LINE_CHART', 'Line Chart'), ('TABLE', 'Table'), ('NUMBER', 'Number'), ('TEXT', 'Text'), ('SELECT_ONE', 'Select One')], default='SELECT_ONE', max_length=50)),
                ('chart_config', models.TextField(blank=True, default='{}')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.DataSource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.Team')),
            ],
        ),
    ]
