# Generated by Django 2.1.5 on 2019-02-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0002_question_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='on_demand',
            field=models.BooleanField(default=False),
        ),
    ]
